### ISSUE TITLE
Extension does not work with HTTPS Everywhere

### ISSUE THREAD

**Issue by Aealo** [jshackles/Enhanced_Steam#1445] opened 2017-09-24 14:00 UTC
Hello,
I have noticed that Enhanced Steam does not work when HTTPS Everywhere extension is enabled in Chrome. When its enables ES will show this error "One or more requests failed:
http://api.enhancedsteam.com/pricev3/?bundleid=&subs=53984,49961,&stores=amazonus,bundlestars,chrono,direct2drive,dlgamer,dreamgame,fireflower,gamebillet,gamejolt,gamersgate,gamesplanet,gog,humblestore,humblewidgets,impulse,indiegalastore,indiegamestand,itchio,macgamestore,newegg,nuuvem,origin,paradox,savemi,silagames,squenix,steam,uplay,wingamestore,&cc=SK&appid=274940&coupon=true". After disabling HTTPS Everywhere ES starts working again. Is it possible to fix this?

**Comment by Ickerday** [comment] 2017-09-25 09:37
Not a fix, but it is possible to turn the rule off for EnhancedSteam.

**Comment by Aealo** [comment] 2017-09-25 09:38
yeah did that too, but it would be better if it worked without making exceptions

**Comment by seeeeew** [comment] 2017-09-25 23:37
Duplicate of #1319, should be closed.

**Comment by l34kr** [comment] 2017-10-18 02:25
Close this issue please.

**Comment by seeeeew** [comment] 2017-10-18 10:19
It will be automatically closed when the changes are merged into the master branch.

**Closed** 2017-10-23 21:05 UTC
