### ISSUE TITLE
[BUG] Achievements section, "Date Unlocked" not working

### ISSUE THREAD

**Issue by pepe1987** [jshackles/Enhanced_Steam#777] opened 2015-08-17 13:12 UTC
Window 7
Chrome 43.0.2357.132 m

Error: Uncaught TypeError: Cannot read property '3' of null

File: enhancedsteam.js 
Version: 7.7
Line: https://github.com/jshackles/Enhanced_Steam/blob/master/enhancedsteam.js#L6492

**Comment by fadillzzz** [comment] 2015-08-17 13:47
Possibly a duplicate of #773

**Comment by seeeeew** [comment] 2015-08-19 15:13
If this still happened after f670c7bf208cdd5ef4e4a91ee01ac07275598c10 it should be fixed by 5efcf234caaf5786e6cdaf027269fa697b853851.

**Closed** 2015-08-21 03:50 UTC
