### ISSUE TITLE
ES Not Load when using 

### ISSUE THREAD

**Issue by Tir-ta** [jshackles/Enhanced_Steam#1432] opened 2017-09-05 18:58 UTC
When i load any games pages, ES can't show information about price anymore.

I'm curious, so i try to turn off HTTPS everywhere and now it works really well.

There is no problem at all before. I have no idea if it's bug or not.

```
One or more requests failed:
http://api.enhancedsteam.com/storepagedata/?appid=433340&r_all=13474&r_pos=12905&r_stm=11161&mcurl=http://www.metacritic.com/game/pc/slime-rancher?ftag=MCD-06-10aaa1f&oc
http://api.enhancedsteam.com/pricev3/?bundleid=&subs=90214,&stores=amazonus,bundlestars,chrono,direct2drive,dlgamer,dreamgame,fireflower,gamebillet,gamejolt,gamersgate,gamesplanet,gog,humblestore,humblewidgets,impulse,indiegalastore,indiegamestand,itchio,macgamestore,newegg,nuuvem,origin,paradox,savemi,silagames,squenix,steam,uplay,wingamestore,&cc=ID&appid=433340&coupon=true
```

Thanks in advance.

**Comment by Tir-ta** [comment] 2017-09-06 02:08
![untitled](https://user-images.githubusercontent.com/19362604/30091248-df770216-92e2-11e7-86ee-fea65a6787e0.jpg)

I found the solution... Sorry to bother you.

**Comment by seeeeew** [comment] 2017-09-25 23:37
Duplicate of #1319, should be closed.

**Closed** 2017-10-23 21:05 UTC
