### ISSUE TITLE
Opera js errors

### ISSUE THREAD

**Issue by DannieBGoode** [jshackles/Enhanced_Steam#1455] opened 2017-10-09 20:27 UTC
When opening a game store page in the opera browser (last version 48.0) there a lot of js errors in the console and the application does not load properly.

![Example](https://image.prntscr.com/image/2RmuUxGBRS_bxoCHWAG7Xw.png)

This is not limited to the opera extension uploaded to its store, but also by donwloading master from github and trying to load it manually or by installing the chrome extension of enhanced steam in Opera.

**Comment by l34kr** [comment] 2017-10-17 23:06
I don't have this issue with Opera v48 and EnhancedSteam v9.5.
Extension functionalities load properly and the only issues reported are from Steam or Google Analytics directly. 
Hope this helps. Enhanced Steam version 9.6 is dev at the moment, isn't it?

**Comment by DannieBGoode** [comment] 2017-10-19 17:21
Any product page is returning me this errors, for example:
http://store.steampowered.com/app/243040/Startopia/

![image](https://user-images.githubusercontent.com/4180198/31784570-7dc5b1ce-b502-11e7-9df8-bddd19522977.png)

This is with the version of Enhanced steam uploaded as Opera Extensions

**Comment by seeeeew** [comment] 2017-10-19 18:07
Can you retry with the dev branch or with all other extensions disabled?

**Comment by DannieBGoode** [comment] 2017-10-19 18:12
I've just verified, this is the conflicting extension:
https://addons.opera.com/en/extensions/details/https-everywhere/

disabling it allows Steam Enhancer to work. Any chance we could somehow have them both working at the same time?

**Comment by seeeeew** [comment] 2017-10-19 18:13
I edited my post while you commented. Should be working in the next release.

**Comment by seeeeew** [comment] 2017-10-19 18:14
This is a duplicate of #1319, so it can be closed.

**Closed** 2017-10-19 18:19 UTC
