### ISSUE TITLE
Unknown issues

### ISSUE THREAD

**Issue by ScoobyJD** [jshackles/Enhanced_Steam#1359] opened 2017-05-28 21:48 UTC
Thought I would present these I have noticed for some time now.
![enhancedsteam](https://cloud.githubusercontent.com/assets/5624644/26532398/dccfd16e-43cd-11e7-9384-1719d9599cbd.jpg)

**Comment by jshackles** [comment] 2017-05-28 23:07
Are you using HTTPS Everywhere?  This is a possible duplicate of #1319

**Comment by ScoobyJD** [comment] 2017-05-29 00:08
Yes, I am. Should I disable it for steam?

**Comment by ScoobyJD** [comment] 2017-05-29 00:10
Confirmed that disabling fixes the problem as stated in duplicate. Thanks! Didn't understand what all that code meant. Noob out :-( lol

**Closed** 2017-06-19 18:20 UTC
