### ISSUE TITLE
Quick Sell Is Gone

### ISSUE THREAD

**Issue by vidmavidma** [jshackles/Enhanced_Steam#1400] opened 2017-07-16 19:33 UTC
I've tried the following:
* Changing browsers (from Firefox to Chrome)
* Clearing cached data
* Resetting options
* Redownloading ES

"Show Quick Sale buttons on Steam Community items in inventory" is checked in options and I only use one account. I'm out of options, could anyone help?

**Comment by jshackles** [comment] 2017-07-24 17:31
Duplicate of #1387

**Closed by jshackles** 2017-07-24 17:31 UTC
